name = "OVERLAY2022"
uuid = "ef129194-a226-4d8a-b575-62ba8eb377d7"
authors = ["Mauro MILELLA", "Giovanni PAGLIARINI", "Andrea PARADISO", "Eduard I. STAN"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
